export const COLLABORATOR_MANAGEMENT_KEY_IN_STORE = 'collaborator_management';

export const GET_ALL_COLLABORATORS = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/GET_ALL_COLLABORATORS`;
export const GET_ALL_COLLABORATORS_SUCCESS = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/GET_ALL_COLLABORATORS_SUCCESS`;
export const GET_ALL_COLLABORATORS_FAILURE = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/GET_ALL_COLLABORATORS_FAILURE`;

export const CREATE_COLLABORATOR = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/CREATE_COLLABORATOR`;
export const CREATE_COLLABORATOR_SUCCESS = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/CREATE_COLLABORATOR_SUCCESS`;
export const CREATE_COLLABORATOR_FAILURE = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/CREATE_COLLABORATOR_FAILURE`;

export const UPDATE_COLLABORATOR = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/UPDATE_COLLABORATOR`;
export const UPDATE_COLLABORATOR_SUCCESS = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/UPDATE_COLLABORATOR_SUCCESS`;
export const UPDATE_COLLABORATOR_FAILURE = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/UPDATE_COLLABORATOR_FAILURE`;

export const DELETE_COLLABORATOR = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/DELETE_COLLABORATOR`;
export const DELETE_COLLABORATOR_SUCCESS = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/DELETE_COLLABORATOR_SUCCESS`;
export const DELETE_COLLABORATOR_FAILURE = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/DELETE_COLLABORATOR_FAILURE`;

export const COLLABORATOR_ADD_CLEAR = `${COLLABORATOR_MANAGEMENT_KEY_IN_STORE}/COLLABORATOR_ADD_CLEAR`;
