export const MANAGE_STUDENT_KEY_IN_STORE = 'manage_student';

export const GET_ALL_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_ALL_STUDENT`;
export const GET_ALL_STUDENT_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_ALL_STUDENT_SUCCESS`;
export const GET_ALL_STUDENT_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_ALL_STUDENT_FAILURE`;

export const CREATE_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/CREATE_STUDENT`;
export const CREATE_STUDENT_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/CREATE_STUDENT_SUCCESS`;
export const CREATE_STUDENT_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/CREATE_STUDENT_FAILURE`;
export const UPDATE_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/UPDATE_STUDENT`;
export const UPDATE_STUDENT_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/UPDATE_STUDENT_SUCCESS`;
export const UPDATE_STUDENT_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/UPDATE_STUDENT_FAILURE`;

export const DELETE_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/DELETE_STUDENT`;
export const DELETE_STUDENT_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/DELETE_STUDENT_SUCCESS`;
export const DELETE_STUDENT_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/DELETE_STUDENT_FAILURE`;

export const GET_STUDENT_BY_ID = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_STUDENT_BY_ID`;
export const GET_STUDENT_BY_ID_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_STUDENT_BY_ID_SUCCESS`;
export const GET_STUDENT_BY_ID_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_STUDENT_BY_ID_FAILURE`;

export const GET_TRANSACTION_LIST = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_TRANSACTION_LIST`;
export const GET_TRANSACTION_LIST_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_TRANSACTION_LIST_SUCCESS`;
export const GET_TRANSACTION_LIST_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/GET_TRANSACTION_LIST_FAILURE`;

export const CREATE_TRANSACTION = `${MANAGE_STUDENT_KEY_IN_STORE}/CREATE_TRANSACTION`;
export const CREATE_TRANSACTION_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/CREATE_TRANSACTION_SUCCESS`;
export const CREATE_TRANSACTION_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/CREATE_TRANSACTION_FAILURE`;

export const UPDATE_TRANSACTION = `${MANAGE_STUDENT_KEY_IN_STORE}/UPDATE_TRANSACTION`;
export const UPDATE_TRANSACTION_SUCCESS = `${MANAGE_STUDENT_KEY_IN_STORE}/UPDATE_TRANSACTION_SUCCESS`;
export const UPDATE_TRANSACTION_FAILURE = `${MANAGE_STUDENT_KEY_IN_STORE}/UPDATE_TRANSACTION_FAILURE`;

export const CLEAR_TRANSACTION_LIST = `${MANAGE_STUDENT_KEY_IN_STORE}/CLEAR_TRANSACTION_LIST`;

export const CLEAR_ALL_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/CLEAR_ALL_STUDENT`;
export const CLEAR_CREATE_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/CLEAR_CREATE_STUDENT`;
export const CLEAR_UPDATE_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/CLEAR_UPDATE_STUDENT`;
export const CLEAR_DELETE_STUDENT = `${MANAGE_STUDENT_KEY_IN_STORE}/CLEAR_DELETE_STUDENT`;
