export const ONBOARDING_KEY_STORE = 'onboarding';
export const START_ONBOARDING_PROCESS = `${ONBOARDING_KEY_STORE}/START_ONBOARDING_PROCESS`;
export const SET_DATA_USER = `${ONBOARDING_KEY_STORE}/SET_DATA_USER`;
export const RESET_SET_DATA_USER = `${ONBOARDING_KEY_STORE}/RESET_SET_DATA_USER`;
export const SET_DATA_SCHOOL = `${ONBOARDING_KEY_STORE}/SET_DATA_SCHOOL`;
export const RESET_SET_DATA_SCHOOL = `${ONBOARDING_KEY_STORE}/RESET_SET_DATA_SCHOOL`;
export const ONBOARDING_PROCESS_SUCCESS = `${ONBOARDING_KEY_STORE}/ONBOARDING_PROCESS_SUCCESS`;
export const SUBMIT_ONBOARDING_PROCESS = `${ONBOARDING_KEY_STORE}/SUBMIT_ONBOARDING_PROCESS`;

export const ONBOARDING_PROCESS_ERROR = `${ONBOARDING_KEY_STORE}/ONBOARDING_PROCESS_ERROR`;
export const CLEAR_ONBOARDING_PROCESS = `${ONBOARDING_KEY_STORE}/CLEAR_ONBOARDING_PROCESS`;
