export const ROLE_MANAGEMENT_KEY_IN_STORE = 'role_management';

export const GET_ALL_ROLES = `${ROLE_MANAGEMENT_KEY_IN_STORE}/GET_ALL_ROLES`;
export const GET_ALL_ROLES_SUCCESS = `${ROLE_MANAGEMENT_KEY_IN_STORE}/GET_ALL_ROLES_SUCCESS`;
export const GET_ALL_ROLES_FAILURE = `${ROLE_MANAGEMENT_KEY_IN_STORE}/GET_ALL_ROLES_FAILURE`;

export const CREATE_ROLE = `${ROLE_MANAGEMENT_KEY_IN_STORE}/CREATE_ROLE`;
export const CREATE_ROLE_SUCCESS = `${ROLE_MANAGEMENT_KEY_IN_STORE}/CREATE_ROLE_SUCCESS`;
export const CREATE_ROLE_FAILURE = `${ROLE_MANAGEMENT_KEY_IN_STORE}/CREATE_ROLE_FAILURE`;
export const UPDATE_ROLE = `${ROLE_MANAGEMENT_KEY_IN_STORE}/UPDATE_ROLE`;
export const UPDATE_ROLE_SUCCESS = `${ROLE_MANAGEMENT_KEY_IN_STORE}/UPDATE_ROLE_SUCCESS`;
export const UPDATE_ROLE_FAILURE = `${ROLE_MANAGEMENT_KEY_IN_STORE}/UPDATE_ROLE_FAILURE`;

export const DELETE_ROLE = `${ROLE_MANAGEMENT_KEY_IN_STORE}/DELETE_ROLE`;
export const DELETE_ROLE_SUCCESS = `${ROLE_MANAGEMENT_KEY_IN_STORE}/DELETE_ROLE_SUCCESS`;
export const DELETE_ROLE_FAILURE = `${ROLE_MANAGEMENT_KEY_IN_STORE}/DELETE_ROLE_FAILURE`;

export const CLEAR_ALL_ROLES = `${ROLE_MANAGEMENT_KEY_IN_STORE}/CLEAR_ALL_ROLES`;
