export const BVG_COMMON_KEY_IN_STORE = 'BVG_COMMON_KEY_IN_STORE';
export const SHOW_LOADER = `${BVG_COMMON_KEY_IN_STORE}/SHOW_LOADER`;
export const HIDE_LOADER = `${BVG_COMMON_KEY_IN_STORE}/HIDE_LOADER`;
