export const PACKS_KEY_IN_STORE = 'pack-management';
export const GET_ALL_PACKS = `${PACKS_KEY_IN_STORE}/LIST_OF_PACKS`;
export const GET_ALL_PACKS_SUCCESS = `${PACKS_KEY_IN_STORE}/LIST_PACKS_SUCCESS`;
export const GET_ALL_PACKS_FAILED = `${PACKS_KEY_IN_STORE}/LIST_PACKS_FAILED`;

export const GET_ONE_PACK = `${PACKS_KEY_IN_STORE}/GET_ONE_PACK`;
export const GET_ONE_PACK_SUCCESS = `${PACKS_KEY_IN_STORE}/GET_ONE_PACK_SUCCESS`;
export const GET_ONE_PACK_FAILED = `${PACKS_KEY_IN_STORE}/GET_ONE_PACK_FAILED`;

export const CREATE_PACK = `${PACKS_KEY_IN_STORE}/CREATE_PACK`;
export const CREATE_PACK_SUCCESS = `${PACKS_KEY_IN_STORE}/CREATE_PACK_SUCCESS`;
export const CREATE_PACK_FAILED = `${PACKS_KEY_IN_STORE}/CREATE_PACK_FAILED`;

export const UPDATE_PACK = `${PACKS_KEY_IN_STORE}/UPDATE_PACK`;
export const UPDATE_PACK_SUCCESS = `${PACKS_KEY_IN_STORE}/UPDATE_PACK_SUCCESS`;
export const UPDATE_PACK_FAILED = `${PACKS_KEY_IN_STORE}/UPDATE_PACK_FAILED`;

export const DELETE_PACK = `${PACKS_KEY_IN_STORE}/DELETE_PACK`;
export const DELETE_PACK_SUCCESS = `${PACKS_KEY_IN_STORE}/DELETE_PACK_SUCCESS`;
export const DELETE_PACK_FAILED = `${PACKS_KEY_IN_STORE}/DELETE_PACK_FAILED`;

export const CLEAR_ADD_PACKS = `${PACKS_KEY_IN_STORE}/CLEAR_PACKS`;
export const CLEAR_UPDATE_PACK = `${PACKS_KEY_IN_STORE}/CLEAR_UPDATE_PACK`;
export const CLEAR_DELETE_PACK = `${PACKS_KEY_IN_STORE}/CLEAR_DELETE_PACK`;
export const CLEAR_PACKS_LIST = `${PACKS_KEY_IN_STORE}/CLEAR_PACKS_LIST`;
