export const USER_PACK_KEY_IN_STORE = 'userPackManagement';

export const USER_PACK_FIND_MY_PACK_REQUEST = `${USER_PACK_KEY_IN_STORE}/FIND_MY_PACK_REQUEST`;
export const USER_PACK_FIND_MY_PACK_SUCCESS = `${USER_PACK_KEY_IN_STORE}/FIND_MY_PACK_SUCCESS`;
export const USER_PACK_FIND_MY_PACK_FAILURE = `${USER_PACK_KEY_IN_STORE}/FIND_MY_PACK_FAILURE`;

export const USER_PACK_RENEW_REQUEST = `${USER_PACK_KEY_IN_STORE}/RENEW_REQUEST`;
export const USER_PACK_RENEW_SUCCESS = `${USER_PACK_KEY_IN_STORE}/RENEW_SUCCESS`;
export const USER_PACK_RENEW_FAILURE = `${USER_PACK_KEY_IN_STORE}/RENEW_FAILURE`;

export const USER_PACK_PAY_REQUEST = `${USER_PACK_KEY_IN_STORE}/PAY_REQUEST`;
export const USER_PACK_PAY_SUCCESS = `${USER_PACK_KEY_IN_STORE}/PAY_SUCCESS`;
export const USER_PACK_PAY_FAILURE = `${USER_PACK_KEY_IN_STORE}/PAY_FAILURE`;
